In [1]:
import numpy as np # This is how you can import packages in python.

In [2]:
# np.array converts any array-like object to a numpy array
x=np.array([1,2,3,4]) 
#x=[1,2,3,4]
y=2*x
print("{}\n{}".format(x,y))

[1 2 3 4]
[2 4 6 8]


In [3]:
x=(1,2,3,4) # with list
y=2*x
print("{}\n{}".format(x,y))

(1, 2, 3, 4)
(1, 2, 3, 4, 1, 2, 3, 4)


In [4]:
# gives array of range
x = np.arange(0,100, 2) 
print(x[[4,5,6,7,8,9,10]])

[ 8 10 12 14 16 18 20]


In [5]:
# Not possible in List
x = [1,2,3,4,5,6,7,8,9,10]  
print(x[[0,1,2]])

TypeError: list indices must be integers or slices, not list

In [6]:
# Multidimensinal Array
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# number of dimensions. This is a 2D array
print(x.ndim)
# Shape of array
print(x.shape) 
# Total number of elements in array (product of elements in shape)
print(x.size) 

2
(3, 3)
9


In [8]:
# Array Multiplication (Simple)
x*x

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [10]:
# Array Multiplication (Matrix)
np.matrix(x)*np.matrix(x)

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [15]:
# Conditional Check
x>3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [16]:
y=np.copy(x) # Note: No new array is generated.
y[y>3]=0
y

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [17]:
x=np.array([0,1,2,3,4,5,6,7,0.5,0.6])
indices=np.where(x==0.5)
x[indices]

array([0.5])

In [18]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
x[1,:]

array([4, 5, 6])

In [19]:
np.arange(0,1,0.1) # start, stop, step

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [20]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])